// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.31.0
// source: pb/dcache.proto

package __

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Request struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Group         string                 `protobuf:"bytes,1,opt,name=group" json:"group,omitempty"`
	Key           string                 `protobuf:"bytes,2,opt,name=key" json:"key,omitempty"`
	Value         []byte                 `protobuf:"bytes,3,opt,name=value" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Request) Reset() {
	*x = Request{}
	mi := &file_pb_dcache_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Request) ProtoMessage() {}

func (x *Request) ProtoReflect() protoreflect.Message {
	mi := &file_pb_dcache_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Request.ProtoReflect.Descriptor instead.
func (*Request) Descriptor() ([]byte, []int) {
	return file_pb_dcache_proto_rawDescGZIP(), []int{0}
}

func (x *Request) GetGroup() string {
	if x != nil {
		return x.Group
	}
	return ""
}

func (x *Request) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *Request) GetValue() []byte {
	if x != nil {
		return x.Value
	}
	return nil
}

type ResponseForGet struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Value         []byte                 `protobuf:"bytes,1,opt,name=value" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResponseForGet) Reset() {
	*x = ResponseForGet{}
	mi := &file_pb_dcache_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResponseForGet) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResponseForGet) ProtoMessage() {}

func (x *ResponseForGet) ProtoReflect() protoreflect.Message {
	mi := &file_pb_dcache_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResponseForGet.ProtoReflect.Descriptor instead.
func (*ResponseForGet) Descriptor() ([]byte, []int) {
	return file_pb_dcache_proto_rawDescGZIP(), []int{1}
}

func (x *ResponseForGet) GetValue() []byte {
	if x != nil {
		return x.Value
	}
	return nil
}

var File_pb_dcache_proto protoreflect.FileDescriptor

const file_pb_dcache_proto_rawDesc = "" +
	"\n" +
	"\x0fpb/dcache.proto\x12\x02pd\x1a\x1bgoogle/protobuf/empty.proto\"G\n" +
	"\aRequest\x12\x14\n" +
	"\x05group\x18\x01 \x01(\tR\x05group\x12\x10\n" +
	"\x03key\x18\x02 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x03 \x01(\fR\x05value\"&\n" +
	"\x0eResponseForGet\x12\x14\n" +
	"\x05value\x18\x01 \x01(\fR\x05value2\x91\x01\n" +
	"\x06DCache\x12(\n" +
	"\x03Get\x12\v.pd.Request\x1a\x12.pd.ResponseForGet\"\x00\x12,\n" +
	"\x03Set\x12\v.pd.Request\x1a\x16.google.protobuf.Empty\"\x00\x12/\n" +
	"\x06Delete\x12\v.pd.Request\x1a\x16.google.protobuf.Empty\"\x00B\tZ\x02./\x92\x03\x02\b\x02b\beditionsp\xe8\a"

var (
	file_pb_dcache_proto_rawDescOnce sync.Once
	file_pb_dcache_proto_rawDescData []byte
)

func file_pb_dcache_proto_rawDescGZIP() []byte {
	file_pb_dcache_proto_rawDescOnce.Do(func() {
		file_pb_dcache_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pb_dcache_proto_rawDesc), len(file_pb_dcache_proto_rawDesc)))
	})
	return file_pb_dcache_proto_rawDescData
}

var file_pb_dcache_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_pb_dcache_proto_goTypes = []any{
	(*Request)(nil),        // 0: pd.Request
	(*ResponseForGet)(nil), // 1: pd.ResponseForGet
	(*emptypb.Empty)(nil),  // 2: google.protobuf.Empty
}
var file_pb_dcache_proto_depIdxs = []int32{
	0, // 0: pd.DCache.Get:input_type -> pd.Request
	0, // 1: pd.DCache.Set:input_type -> pd.Request
	0, // 2: pd.DCache.Delete:input_type -> pd.Request
	1, // 3: pd.DCache.Get:output_type -> pd.ResponseForGet
	2, // 4: pd.DCache.Set:output_type -> google.protobuf.Empty
	2, // 5: pd.DCache.Delete:output_type -> google.protobuf.Empty
	3, // [3:6] is the sub-list for method output_type
	0, // [0:3] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_pb_dcache_proto_init() }
func file_pb_dcache_proto_init() {
	if File_pb_dcache_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pb_dcache_proto_rawDesc), len(file_pb_dcache_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_pb_dcache_proto_goTypes,
		DependencyIndexes: file_pb_dcache_proto_depIdxs,
		MessageInfos:      file_pb_dcache_proto_msgTypes,
	}.Build()
	File_pb_dcache_proto = out.File
	file_pb_dcache_proto_goTypes = nil
	file_pb_dcache_proto_depIdxs = nil
}
