// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v6.31.0
// source: pb/dcache.proto

package __

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	DCache_Get_FullMethodName    = "/pd.DCache/Get"
	DCache_Set_FullMethodName    = "/pd.DCache/Set"
	DCache_Delete_FullMethodName = "/pd.DCache/Delete"
)

// DCacheClient is the client API for DCache service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type DCacheClient interface {
	Get(ctx context.Context, in *Request, opts ...grpc.CallOption) (*ResponseForGet, error)
	Set(ctx context.Context, in *Request, opts ...grpc.CallOption) (*emptypb.Empty, error)
	Delete(ctx context.Context, in *Request, opts ...grpc.CallOption) (*emptypb.Empty, error)
}

type dCacheClient struct {
	cc grpc.ClientConnInterface
}

func NewDCacheClient(cc grpc.ClientConnInterface) DCacheClient {
	return &dCacheClient{cc}
}

func (c *dCacheClient) Get(ctx context.Context, in *Request, opts ...grpc.CallOption) (*ResponseForGet, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ResponseForGet)
	err := c.cc.Invoke(ctx, DCache_Get_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dCacheClient) Set(ctx context.Context, in *Request, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, DCache_Set_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dCacheClient) Delete(ctx context.Context, in *Request, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, DCache_Delete_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// DCacheServer is the server API for DCache service.
// All implementations must embed UnimplementedDCacheServer
// for forward compatibility.
type DCacheServer interface {
	Get(context.Context, *Request) (*ResponseForGet, error)
	Set(context.Context, *Request) (*emptypb.Empty, error)
	Delete(context.Context, *Request) (*emptypb.Empty, error)
	mustEmbedUnimplementedDCacheServer()
}

// UnimplementedDCacheServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedDCacheServer struct{}

func (UnimplementedDCacheServer) Get(context.Context, *Request) (*ResponseForGet, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Get not implemented")
}
func (UnimplementedDCacheServer) Set(context.Context, *Request) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Set not implemented")
}
func (UnimplementedDCacheServer) Delete(context.Context, *Request) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Delete not implemented")
}
func (UnimplementedDCacheServer) mustEmbedUnimplementedDCacheServer() {}
func (UnimplementedDCacheServer) testEmbeddedByValue()                {}

// UnsafeDCacheServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to DCacheServer will
// result in compilation errors.
type UnsafeDCacheServer interface {
	mustEmbedUnimplementedDCacheServer()
}

func RegisterDCacheServer(s grpc.ServiceRegistrar, srv DCacheServer) {
	// If the following call pancis, it indicates UnimplementedDCacheServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&DCache_ServiceDesc, srv)
}

func _DCache_Get_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Request)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DCacheServer).Get(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DCache_Get_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DCacheServer).Get(ctx, req.(*Request))
	}
	return interceptor(ctx, in, info, handler)
}

func _DCache_Set_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Request)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DCacheServer).Set(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DCache_Set_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DCacheServer).Set(ctx, req.(*Request))
	}
	return interceptor(ctx, in, info, handler)
}

func _DCache_Delete_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Request)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DCacheServer).Delete(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DCache_Delete_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DCacheServer).Delete(ctx, req.(*Request))
	}
	return interceptor(ctx, in, info, handler)
}

// DCache_ServiceDesc is the grpc.ServiceDesc for DCache service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var DCache_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "pd.DCache",
	HandlerType: (*DCacheServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Get",
			Handler:    _DCache_Get_Handler,
		},
		{
			MethodName: "Set",
			Handler:    _DCache_Set_Handler,
		},
		{
			MethodName: "Delete",
			Handler:    _DCache_Delete_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "pb/dcache.proto",
}
